### ISSUE TITLE
[QST] Passing an integer as a template parameter

### ISSUE THREAD

**Issue by PointKernel** [allisonvacanti/nvbench#7]
```cpp
// SIZE can be 1, 2, 4, 8, 16 or 32
template <typename T, int SIZE>
void nvbench_test(nvbench::state &state)
{
  ...
}
```

Is there a way to pass integers (or values) as template parameters to a target benchmark in nvbench? I.e., passing `SIZE` to `nvbench_test` in the above example.

**Comment by allisonvacanti** [comment]
Yes -- the `enum_type_axis` utilities work for integral types, too. See [this benchmark](https://github.com/allisonvacanti/nvbench/blob/34479b311643205b33b1f5620b54b9e3eeea599d/examples/enums.cu#L190-L215) for an example.

**Comment by PointKernel** [comment]
Great, exactly what I'm looking for.

Thanks!
